name: Build Kernel with KSU (Optional)

on:
  workflow_dispatch:
    inputs:
      device:
        description: '选择设备代号'
        required: true
        default: 'pipa'
        type: choice
        options:
          - psyche
          - umi
          - munch
          - lmi
          - cmi
          - cas
          - apollo
          - alioth
          - elish
          - enuma
          - dagu
          - pipa
      include_ksu:
        description: '是否包含KSU'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
      include_kpm:
        description: '是否包含KPM'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        fetch-depth: 1  # 相当于 git clone --depth=1，加快速度

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git curl wget bison flex zip bc cpio libssl-dev ccache python-is-python3 unzip

    - name: Setup proton-clang toolchain
      run: |
        mkdir -p $HOME/proton-clang
        cd $HOME/proton-clang
        wget https://github.com/kdrag0n/proton-clang/archive/refs/tags/20210522.zip
        unzip 20210522.zip
        cd $GITHUB_WORKSPACE

    - name: Build kernel
      run: |
        BUILD_ARGS="${{ github.event.inputs.device }}"
        if [ "${{ github.event.inputs.include_ksu }}" = "true" ]; then
        BUILD_ARGS="$BUILD_ARGS ksu"
        fi
        if [ "${{ github.event.inputs.include_kpm }}" = "true" ]; then
        BUILD_ARGS="$BUILD_ARGS kpm"
        fi
        bash build.sh $BUILD_ARGS

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.inputs.device }}${{ github.event.inputs.include_ksu == 'true' && '-ksu' || '' }}-kernel
        path: |
          *.zip
          out/arch/arm64/boot/Image
          out/arch/arm64/boot/dtb
